# name: Ninja-ddd-practice CI/CD Pipeline

# on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]

# jobs:
#   build-and-push:
#     runs-on: ubuntu-latest
    
#     steps:
#     - uses: actions/checkout@v2
    
#     - name: Set up JDK 17
#       uses: actions/setup-java@v2
#       with:
#         java-version: '17'
#         distribution: 'adopt'
    
#     - name: Build ninja-backend
#       run: |
#         cd ./ninja-backend/  # 後端程式碼在ninja-backend目錄
#         chmod +x mvnw
#         ./mvnw clean package -DskipTests
    
#     - name: Set up Node.js
#       uses: actions/setup-node@v2
#       with:
#         node-version: '19.4.0'
    
#     - name: Build ninja-frontend
#       run: |
#         cd ./ninja-frontend  # 前端程式碼在ninja-frontend目錄
#         npm install --legacy-peer-deps
#         npm run build -- --configuration production
    
#     - name: Log in to Docker Hub
#       uses: docker/login-action@v1
#       with:
#         username: ${{ secrets.DOCKER_HUB_USERNAME }}
#         password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
#     - name: Build and push backend Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: ./backend
#         push: true
#         tags: vincentkai/backend:latest
    
#     - name: Build and push frontend Docker image
#       uses: docker/build-push-action@v2
#       with:
#         context: ./frontend
#         push: true
#         tags: vincentkai/frontend:latest

name: Ninja-ddd-practice CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Build ninja-backend
      run: |
        cd ninja-backend
        if [ -f "mvnw" ]; then
          chmod +x mvnw
          ./mvnw clean package -DskipTests
        else
          mvn clean package -DskipTests
        fi
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.4.0'
    
    - name: Build ninja-frontend
      run: |
        cd ninja-frontend
        npm install --legacy-peer-deps
        npm run build -- --configuration production
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./ninja-backend
        file: ./ninja-backend/Dockerfile
        push: true
        tags: vincentkai/backend:latest
    
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./ninja-frontend
        file: ./ninja-frontend/Dockerfile
        push: true
        tags: vincentkai/frontend:latest