name: Ninja-ddd-practice CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Generate version number
      id: version
      run: |
        echo "VERSION=$(date +'%Y.%m.%d')-${GITHUB_RUN_NUMBER}-${GITHUB_SHA::7}" >> $GITHUB_OUTPUT

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
    
    - name: Build ninja-backend
      run: |
        cd ./ninja-backend/  
        chmod +x mvnw
        ./mvnw clean package -DskipTests
    
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '19.4.0'
    
    - name: Build ninja-frontend
      run: |
        cd ./ninja-frontend  
        npm install --legacy-peer-deps
        npm run build -- --configuration production
    
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    
    - name: Build and push backend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./ninja-backend
        push: true
        tags: |
          vincentkai/ninja-backend:latest
          vincentkai/ninja-backend:${{ steps.version.outputs.VERSION }}
    
    - name: Build and push frontend Docker image
      uses: docker/build-push-action@v2
      with:
        context: ./ninja-frontend
        push: true
        tags: |
          vincentkai/ninja-frontend:latest
          vincentkai/ninja-frontend:${{ steps.version.outputs.VERSION }}
          - name: Send email notification
          uses: dawidd6/action-send-mail@v2
          with:
            server_address: smtp.gmail.com
            server_port: 465
            username: ${{secrets.EMAIL_USER}}
            password: ${{secrets.EMAIL_PASS}}
            subject: GitHub Actions job result for ${{github.repository}}
            body: |
              Job in ${{github.repository}} finished with status ${{job.status}}.
              
              Commit message: ${{ github.event.head_commit.message }}
              
              See details here: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
            to: mister33221@gmail.com
            from: GitHub Actions
          if: always()